[package]
name = "Blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
async-trait = "0.1.89"
thiserror = "2.0.9"
dashmap = "6.1.0"
bytes = "1.11.0"
byteorder = "1"
rand = "0.9.2"
sha3 = "0.10.8"