[package]
name = "Blockchain"
version = "0.9.6"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", default-features = false, features = ["macros", "rt-multi-thread", "sync", "time"] }
sha3 = "0.10.8"
k256 = "=0.13.4"
rand_core = "=0.6.4"
blockchain_derive = { path = "blockchain_derive" }
dashmap = "6.1.0"
