[package]
name = "Blockchain"
version = "0.7.1"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
async-trait = "0.1.89"
thiserror = "2.0.9"
dashmap = "6.1.0"
bytes = "1.11.0"
borsh = { version =  "1.6.0", features = ["derive"] }
blockchain_derive = { path = "blockchain_derive" }
rand = "0.9.2"
sha3 = "0.10.8"
k256 = "=0.13.4"
rand_core = "=0.6.4"